version: "3.7"

services:
  space_app:
    image: magdielcardoso/space:latest
    command: bundle exec rails s -p 4032 -b 0.0.0.0
    entrypoint: /rails/bin/docker-entrypoint
    ports:
      - "4032:4032"
    volumes:
      - space_storage:/rails/storage
      - space_log:/rails/log
      - space_tmp:/rails/tmp
    networks:
      - pedetudo
    environment:
      - RAILS_MASTER_KEY=74a7a6a9d8652272efa4af482975f526
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_FORCE_SSL=false
      - RAILS_MAX_THREADS=5
      - RAILS_MIN_THREADS=2
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=PT99874166
      - DATABASE_HOST=postgres
      - DATABASE_NAME=space
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.space_app.rule=Host(`space.stacklab.digital`)
        - traefik.http.routers.space_app.entrypoints=websecure
        - traefik.http.routers.space_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.space_app.priority=1
        - traefik.http.routers.space_app.service=space_app
        - traefik.http.services.space_app.loadbalancer.server.port=4032
        - traefik.http.services.space_app.loadbalancer.passhostheader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.space_app.middlewares=sslheader@docker

volumes:
  space_storage:
    external: true
    name: space_storage
  space_log:
    external: true
    name: space_log
  space_tmp:
    external: true
    name: space_tmp

networks:
  pedetudo:
    external: true
    name: pedetudo 